# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
