language: objective-c
# before_install: cd Example && pod install && cd -
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
