language: ruby
sudo: false

cache: bundler
rvm:
  - 2.2.5
  - 2.2.2

# By default, this runs rake on the latest ruby and executes
# bundle install --jobs=3 --retry=3
# rake

script:
 - git fetch --unshallow
 - bundle exec rake
